sudo: required
services:
  - docker

before_install:
  - docker build -t ch3mjor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ch3mjor/react-test npm test -- --coverage

after_success:
  - docker build -t ch3mjor/multi-client ./client
  - docker build -t ch3mjor/multi-nginx ./nginx
  - docker build -t ch3mjor/multi-server ./server
  - docker build -t ch3mjor/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ch3mjor/multi-client:latest
  - docker push ch3mjor/multi-nginx:latest
  - docker push ch3mjor/multi-server:latest
  - docker push ch3mjor/multi-worker:latest